### ISSUE TITLE
Question: only some channels being broadcast to pi

### ISSUE THREAD

**Issue by hughlaw** [kodi-pvr/pvr.vuplus#41]
My setup:

Evo Enfinity x2+ receiver running enigma2 and OpenATV
Raspberry Pi 2,  enigma2 over installed and configured.

I've installed and set up correctly, and I'm able to receive some channels from the enigma2 box, but some channels just show a waiting dialogue, then revert back to the menu without any sign of the channel.
Weirdly, it doesn't always seem to be the same channels that don't work, although freeview channels seem to be the most stable.

Plugging the enigma box directly to a tv, the other channels are working without issue, but they just don't seem to be getting sent through to kodi.

Can anyone point me in the right direction as to why some channels work and others don't?

**Comment by barricas** [comment]
My guess is that the stream has PMT/PAT. I can't watch some channels on kodi too.

I think the addon is missing the part to read this kind of information:
`#EXTVLCOPT:program=123`

With VLC I can view every channel because the webinterface includes this kind of info, but the addon can't parse it.

Though the option is specially for VLC, it is supported in many players.. it would be nice for this to be added to Kodi because it's a deal breaker and I can't find any other player that can play the channels for Android.

**Comment by hughlaw** [comment]
@barricas - Thanks for the reply -  I actually figured out the issue and forgot to update this question in case anyone else comes across it.
It was as simple as switching the Satellite receiver into standby mode. I finally found some information on another thread somewhere but it kind of makes sense really.
I only have a single source from the satellite going into the receiver, so it tended to be channels that were on the same transponder as the channel currently selected on the receiver that would be available in Kodi. If I switched to a channel on a different transponder I'd simply get a black screen.
The Enigma2 settings were set to zap the channel when you switched in Kodi, but since the receiver was also on, this did not appear to be doing anything.
The solution was to make sure the receiver was in standby mode, and everything started working then. Simple, but an absolute pain to figure out... ;)
